config/routes.rb
Rails.application.routes.draw do
  resources :movies
 root to: 'pictures#index'
   resources :pictures do
      collection do
         post :confirm
    end
  end
    resources :pictures do
       resources :comments
    end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show,:edit]
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  resources :movies
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase!}
  has_secure_password
  validates :password, length: {minimum: 6}
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  #指定のユーザをフォローする
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

#フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required,only: [:new, :create]
  def index
    @users=User.all
  end
  def new
    @user= User.new
  end
  def create
    @user=User.new(user_params)
     if @user.save
        redirect_to user_path(@user.id)
     else
        render :new
    end
  end
  def show
     @user=User.find(params[:id])
  end
  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
   @user  = User.find(params[:id])
   @users = @user.followers
   render 'show_follower'
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "つながりを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/_stats.html.erb
 <% @user ||= current_user %>
<div class="stats">
  <%# <a href="<%= following_user_path(@user) %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <%# <a href="<%= followers_user_path(@user) %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/index.html.erb
  <h2>ユーザー</h2>
  <% @users.each do |user| %>
   <% if user.id != current_user.id %>
  <li>
      <div class="item">
        <%= link_to user.name, user %>
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
      </div>
    </li>
    
     <%= user.name %>
    <%= user.email %>
   <li><%= render 'follow_form', user: user %></li>
  <% end %>
<% end %>

app/views/users/new.html.erb

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="narbar">
    <ul class='row'>
        <li class="col-md-6">
       
         <%= image_tag "fake_user.png",:size =>'250x250' %>
         
          
         user_image.picture
        
        </li>
     <% if current_user %>
          <li><%= link_to  @pictures %></li>
          <%= @user.name %>
        <% end %>
     <li class="col-md-6">
        <div class="registrations-new">
          <h1 class="regist-header">新規登録</h1> 
    　      <p class="regist-free">無料</p>

   <%= form_with(model: @user, local: true) do |f| %>  
     <div>
       <%= f.text_field :name,class:'field name-regist', autofocus: true, autocomplete: "First", placeholder: 'user name'  %>
      </div>
     <div>
      <%= f.email_field :email,class:'field email-regist', autocomplete: "email", placeholder: 'Email' %>
      </div>
      <div>
      <%= f.password_field :password,class:'field password-regist',autocomplete: "off", placeholder: "Password" %>
      </div>
       <div>
       <%= f.password_field :password_confirmation,class:'field confirm-regist', autocomplete: "off", placeholder: 'Confirm password' %>
      </div>
     <div class="actions registration-button">
       <%= f.submit "Sign up" %>
    </div>
    <% end %>
          <%= link_to 'Log In', new_session_path %>
        </li>
    </ul>
</div>


app/views/users/show.html.erb
<div class='profile-wrapper'>
<%= image_tag "fake_user.png",:size =>'150x150' %>
<h1><%= @user.name %>のprofile</h1>
<%= render 'stats' %>

<p>メールアドレス: <%= @user.email %></p>
<p>フォローユーザーの一覧</p>

 <% @user.following.each do |user| %>
<table>
<tr class='follow-layout'>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>
</table>
<% end %>

      
    
<p>フォロワーユーザーの一覧</p>
 <% @user.followers.each do |user| %>
<table>
<tr class='follow-layout'>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>


<% if @user.id == current_user.id %>
  <div class="start-picture-form">
    <a href=<%= user_path(current_user.id) %>>
      
    </a>
    <a href=<%= new_picture_path %> class="show-picture-form" >
     <input type="text" placeholder="What's on your mind?(New Post)" class="form_control" readonly="true">
    </a>
  </div>
<% end %>
<%= link_to "ブログを新規作成", pictures_path %>
</div>

