config/routes.rb
Rails.application.routes.draw do
  resources :movies
 root to: 'pictures#index'
   resources :pictures do
      collection do
         post :confirm
    end
  end
    resources :pictures do
       resources :comments
    end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show,:edit]
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  resources :movies
  
end

app/models/picture.rb
class Picture < ApplicationRecord
    validates :image, presence: true
    validates :content, length: { in: 0..200 } 
    validates :content, presence: false
    belongs_to  :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites,source: :user
    has_many :comments, dependent: :destroy 
    mount_uploader :image, ImageUploader
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action  :check_user,:set_picture, only: [:show, :edit, :update, :destroy]
  def index
    @pictures=Picture.all
  end
  def new 
     @picture=Picture.new
  end
  def create
    @picture = current_user.pictures.build(picture_params)
      if params[:back]
         render :new
      else
       if @picture.save
         redirect_to pictures_path, notice: "ブログを作成しました!"      
       else
        render :new
      end
    end
  end
  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end
  def show
    @comments = @picture.comments
    @comment = @picture.comments.build
  end
  def edit
  end
  def update
    if @picture.update(picture_params)
     redirect_to pictures_path, notice: "ブログを編集しました！"
     else
    render :edit
    end
  end
  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"ブログを削除しました！"
  end
  private
  def picture_params
    params.require(:picture).permit(:content,:image,:image_cache)
  end
  def set_picture
    @picture = Picture.find(params[:id])
  end
  def check_user
    if @current_user.nil?
     redirect_to new_session_path unless logged_in?
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
    def logged_in?
        current_user.present?
    end
    def choose_new_or_edit
     if action_name == 'new' || action_name == 'create'
            confirm_pictures_path
     elsif action_name == 'edit'
            picture_path
     end
    end
end

app/views/pictures/_form.html.erb
<div class="pictures-edit">
 <div class = "new-picture">
  <div class="new-picture-top">
      <span>Edit your picture</span>
  </div>
<%= form_with(model: @picture, local: true,url: choose_new_or_edit,class:"picture_wrapper") do |form| %>
    <% if @picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
   <div class='picture_form'>
    <%= image_tag 'fake_user.png',class:'picture_form-image' %>
     <%= current_user.name %><br>
  <%= form.text_area :content, class: 'form-picture-post',placeholder: "What's on your mind, #{current_user.name}?", autofocus: true %> <br/>
   <%= form.label :image, fa_icon('image', type: :solid, text: "Photo", color: 'rgb(66, 103, 178)'), class: 'photo-label' %><br/>
   <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    
  <%= form.file_field :image, class: 'picture-photo' %><br/>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Post",class:'btn-default' %>
  <span>次の画面で確認できます</span>
<% end %>
</div>

<%= link_to "HOME", pictures_path,class:'btn-default' %>
</div>

app/views/pictures/confirm.html.erb
<div class="picture_wrapper">

<h3>以下の内容で、送信する。</h3>
<p>posted by : <%= link_to @picture.user.name %>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
   <%= form.submit '投稿する' %>
<% end %>
  
<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
   <%= form.submit '投稿画面に戻る', name: 'back' %>  
<% end %>
<div>

   
  

app/views/pictures/edit.html.erb
<h2>ブログを編集する</h2>
<%= render 'form' %>

app/views/pictures/index.html.erb
<div class='container'>
   <ul class="row">
     <li class=' col-md-4'>
        <div class= 'left-side-bar'>
         <div  class="side_menu-item">Profile</div>
        <div  class="side_menu-item">友達を検索</div>
        <div  class="side_menu-item">ようこそ</div>
        <div  class="side_menu-item">グループ</div>
        <div  class="side_menu-item">Watch</div>
        <div  class="side_menu-item">思い出</div>
        <div  class="side_menu-item">保存すみ</div>
        <div  class="side_menu-item">ページ</div>
        <div class="side_menu-item">イベント</div>
        <div class="side_menu-item">お気に入り</div>
       <div  class="side_menu-item">もっと見る</div>
       <div  class="side_menu-item">Facebook Pay</div>
       <div  class="side_menu-item">Messenger</div>
       <div  class="side_menu-item">Quest</div>
       </div>
     </li>
    <li class='col-md-4'>  
     <div> 
      <h2>ブログ一覧</h2>
      <%= link_to '新規投稿', new_picture_path ,class:"picture-button" %></li>
        <% @pictures.each do |picture| %>
       <div class='col-md-4'>
        <p>
       </p>
       <p class='picture-content'>
       <%= picture.content %><br/>
       <%= image_tag picture.image.url %><br/>
       </p>
     <div class="favorite-comment-buttons">
       <% favorite = picture.favorites.where("user_id = ?", current_user.id) %>
       <% if favorite.empty? %>
        <%= button_to favorites_path(favorite: {picture_id: picture.id} ), method: :post, class: "favorite-button" do %>
        <%= fa_icon('thumbs-up', type: :regular, text: "favorite") %>
      <% end %>
      <% else %>
        <%= button_to favorite_path(favorite.ids), method: :delete, class: "favorite-button unfavorite" do %>
        <%= fa_icon('thumbs-up', type: :solid, text: "favorite") %>
        <% end %>
      <% end %>
      <button class="comment-button"><i class="far fa-comment-alt"></i> Comment</button>
      </div>
      <%= link_to '確認', picture_path(picture.id),class:"btn-default",date: {"turbolinks"=>false} %>
      </div>
     </div>
     <% end %>
     </li>
   </ul>
</div>

app/views/pictures/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

app/views/pictures/show.html.erb
<p><%= notice %></p>
<div class="picture-show">
  <div class="picture">
    <p class="picture-header">
     <%= link_to distance_of_time_in_words(Time.now, @picture.created_at), @picture, class: 'timestamp' %>
   <div class="picture-content">
    <p> Posted by : <%= @picture.user.name %></p><br/>
    </div>
  
  <% if current_user.id == @picture.user_id %>
    <span class="edit-delete-picture">
      <%= link_to '写真を編集', edit_picture_path(@picture) %>
      <%= link_to '削除', picture_path(@picture.id), method: :delete, data: {confirm: "本当に削除してよろしいでしょうか?"} %>
    </span>

    </div>
  <% end %>
  <p class="post-content">
    <%= image_tag@picture.image.url %>
      <%= @picture.content %><br/>
    </p>

 <button class="comment-button"><i class="far fa-comment-alt"></i> Comment</button>
   <div id="comments_area">
   
    <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'comments/index', locals: { comments: @comments, picture: @picture } %>
    <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'comments/form', locals: { comment: @comment, picture: @picture } %>
    <%= link_to "もどる", pictures_path %>
  </div>
  <div class="favorite-comment-buttons">
   <% unless @picture.user_id == current_user.id %>
   
     <% if @favorite.present? %>
     <%= button_to  favorite_path(id: @favorite.id), method: :delete, class: 'favorite-button unfavorite' do %>
     <%= fa_icon('thumbs-up', type: :regular, text: "favorite") %>
    <% end %>
    <% else %>
      <%= button_to  favorites_path(favorite: {picture_id: @picture.id} ), method: :post, class: "favorite-button" do %>
      <%= fa_icon('thumbs-up', type: :solid, text: "favorite") %>
    <% end %>
    <% end %>

</div>

  
    </div> 
  </div>
  <% end %>

