config/routes.rb
Rails.application.routes.draw do
  resources :movies
 root to: 'pictures#index'
   resources :pictures do
      collection do
         post :confirm
    end
  end
    resources :pictures do
       resources :comments
    end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show,:edit]
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  resources :movies
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
  validates :content, presence: true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
    # 会話はUserの概念をsenderとrecipientに分けた形でアソシエーションする。
    belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
    # 一つの会話はメッセージをたくさん含む一対多。
    has_many :messages, dependent: :destroy
  
    # [:sender_id, :recipient_id]が同じ組み合わせで保存されないようにするためのバリデーションを設定。
    validates_uniqueness_of :sender_id, scope: :recipient_id
  
    # 下記で解説
    scope :between, -> (sender_id,recipient_id) do
      where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
    end
  
    # 下記で解説
    def target_user(current_user)
      if sender_id == current_user.id
        User.find(recipient_id)
      elsif recipient_id == current_user.id
        User.find(sender_id)
      end
    end
  end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  validates :user_id, uniqueness: { scope: :picture_id }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
 validates :title, presence: true, uniqueness: true, length:{ maximum:100}
 validates :production_year,presence: true,uniqueness: false
 validates :running_time,presence: true,uniqueness:false
 validates :rating,presence: true,uniqueness: false
 enum status: {公開前:0, 公開中:1}
end

app/models/picture.rb
class Picture < ApplicationRecord
    validates :image, presence: true
    validates :content, length: { in: 0..200 } 
    validates :content, presence: false
    belongs_to  :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites,source: :user
    has_many :comments, dependent: :destroy 
    mount_uploader :image, ImageUploader
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User" 
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase!}
  has_secure_password
  validates :password, length: {minimum: 6}
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  #指定のユーザをフォローする
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

#フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required,only: [:new, :create]
  def index
    @users=User.all
  end
  def new
    @user= User.new
  end
  def create
    @user=User.new(user_params)
     if @user.save
        redirect_to user_path(@user.id)
     else
        render :new
    end
  end
  def show
     @user=User.find(params[:id])
  end
  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
   @user  = User.find(params[:id])
   @users = @user.followers
   render 'show_follower'
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        current_user.present?
    end
   
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
    def logged_in?
        current_user.present?
    end
    def choose_new_or_edit
     if action_name == 'new' || action_name == 'create'
            confirm_pictures_path
     elsif action_name == 'edit'
            picture_path
     end
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content = "width=device-width">
     <%= favicon_link_tag 'user-logo.png' %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <header class='header-menu'>
    <div class="row">
        <% if logged_in? %>
              <ul class='navbar' >
              <li class="col-sm-5"> <input type="search" id="site-search" 
       placeholder='search'></li>
              <li class="col-sm-3">
              <li><%= link_to 'ユーザー一覧', users_path %></li>
              <%= button_to pictures_path, method: :get, class: "fa fa-home" do %>
              <%= fa_icon('home', type: :regular, text: "HOME") %>
              <% end %></li>
             <li class="col-sm-2">
              <%= button_to user_path(current_user.id), method: :get, class: "fa fa-user" do %>
              <%= fa_icon('user', type: :regular,text: "profile") %>
              <% end %></li>
            <li class="col-sm-1"> 
              <%= button_to session_path(current_user.id), method: :delete, class: "fa fa-sign-out" do %>
              <%= fa_icon('sign-out', type: :regular,text:'logout') %>
              <% end %>
              </li>
               <% else %>
             <li class="col-sm-2">
              <%= button_to new_user_path,:method => :get, class: "fa fa-user-plus" do %>
              <%= fa_icon('sign up', type: :regular,text: "Sign up") %>
              <% end %>
             </li>
             <li class="col-sm-3"> 
               <%= button_to new_session_path, method: :get, class: "fa fa-sign-in" do %>
              <%= fa_icon('sign in', type: :regular,text:'login') %>
              <% end %>
              </li>
             </ul>
          <% end %>
        </div>
  </div>
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
      <% end %> 
   </header>
  

  <%= yield %>
  </body>
 
</html>